# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='imageurl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
